// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SharedBudget.iOS
{
	public partial class EventsViewController : UITableViewController
	{
		public EventsViewController (IntPtr handle) : base (handle)
		{
		}

		partial void AddEvent (UIBarButtonItem sender)
		{
			Console.WriteLine ("add event");
		}
	}
}
